Delete istio CRDs when uninstalling istio. (#1000)
* Delete istio CRDs when uninstalling istio.

This is an attemp to fix the flaky tc of the affiliatedcertification
test suite that has been failing too often lately.

Istio CRDs must be removed when uninstalling istio. Otherwise, this
error might appear when re-installing it:

"If istio is not uninstalled properly, the next installation retry fails
because of this error:
Error: INSTALLATION FAILED: Unable to continue with install:
CustomResourceDefinition "wasmplugins.extensions.istio.io" in namespace
"" exists and cannot be imported into the current release: invalid
ownership metadata; annotation validation error: key
"meta.helm.sh/release-namespace" must equal
"affiliatedcert-tests-hrzzgmvrkr": current value is
"affiliatedcert-tests-maahivhcff"

See https://github.com/istio/istio/issues/43204

Also:
- DeferCleanup func installed before the step that installs istio.
- cmd.Run() changed to cmd.CombinedOutput() so cmd output can be shown
  in the gomega error assertion message. If this fix doesn't work, at
  least we'll get more info from the commands that install/uninstall
  istio.
- Added some error return wrappings and minor code refactors.
- Avoided abrupt exit in some scenarios to allow the normal recovery to
  continue.
- Avoid the need of certsuite repo env var if running in container mode.

* Fix typo.

* Avoid returning err when deleting non existing CRDs.